version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update -y

  build:
    commands:
      - echo "Building"
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  type: zip
  files:
    - '**/*'